    name: GitHub Classroom Workflow

    on:
      push:
        branches:
          - main
    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1.4.3
            with:
                 java-version: 1.7
          - uses: education/autograding@v1
